---
title: "Dicionário de Variáveis"
author: "Vanessa Melo"
date: "Março de 2020"
output: word_document
---

#Variável dependente
tan→  TAN utilizada = 1, TAN não utilizada = 0

#Nível individual
idade_mae→"18-24", "25-29","30-34","35-39","40-44","45-49"

racacor_mae→ Branca, Preta, Amarela ou indígena, Parda 

compx→ Companheiro(a): não, sim

educ_mae→ Escolaridade: Fundamental incompleto, Fundamental completo e médio incompleto, Superior completo

partos_mae→ Número de partos: 1, 2, 3 ou mais 

atiremu→ Atividade remunerada: não, sim 

esf→ Cadastro em unidade Saúde da Família: não ou não sabe, sim 

plano→ Posse de plano de saúde: não, sim 

locpre→ Localização da maioria das consultas de pré-natal: público, privado 

locparto→ Localização do parto: Hospital/maternidade, Outros

dauditiva→ Deficiência auditiva: não, sim

consultas7→ Número de consultas de pré-natal: menos de 7, mais de 7

risco→ Orientação sobre sinais de risco na gravidez: não, sim

sifilis→ Realizou exame de sangue para sífilis: não ou não sabe, sim 

sifparx→ Pedido de exame de sífilis para "parceiro": não, sim

hiv→ Foi solicitado o teste para HIV: não ou não sabe, sim 

#Nível contextual	
p_ext_pobres→ Proporção de extrema pobreza

p_pobres→ Proporção de pobreza

idmh_renda→ Índice de Desenvolvimento Humano Municipal - Dimensão Renda

idmh_logevidade→ Índice de Desenvolvimento Humano Municipal - Dimensão Longevidade

idmh_educacao→ (Índice de Desenvolvimento Humano Municipal - Dimensão Educação

c7→	cobertura mensal de nascidos vivos com 7 ou mais consultas pré-natal

ct→ cobertura mensal da triagem auditiva neonatal

cnt→ cobertura mensal de testes não treponêmicos para sífilis em gestantes

pomif→ proporção mensal de óbitos em mulheres em idade fértil (10 a 49 anos) investigados

poinf→ proporção mensal de óbitos infantis investigados	

taxami→ taxa mensal de mortalidade infantil	

taxasc→ taxa de incidência mensal de sífilis congênita confirmada em menores de 1 ano

#Nível contextual: Variáveis centradas na média
p_ext_pobres_c → Proporção de extrema pobreza centrada na média

c7_c→	cobertura mensal de nascidos vivos com 7 ou mais consultas pré-natal centrada na média

ct_c→ cobertura mensal da triagem auditiva neonatal centrada na média

cnt_c→ cobertura mensal de testes não treponêmicos para sífilis em gestantes centrada na média

pomif_c→ proporção mensal de óbitos em mulheres em idade fértil (10 a 49 anos) investigados centrada na média

taxami_c→ taxa mensal de mortalidade infantil centrada na média

taxasc_c→ taxa de incidência mensal de sífilis congênita confirmada em menores de 1 ano centrada na média

#Variáveis para a construção dos bancos
v0001→ Unidade da Federação

v0024→ Estrato

v0031→ Tipo de área

v0006_pns→ Número de ordem do domicílio na PNS

upa_pns→ Unidade Primária de Amostragem (UPA)

v0028→ Peso do domicílio com correção de não entrevista sem calibração pela 
projeção de população 

v00283→ Domínio de pós-estrato 1 

v00282→ Projeção da população

l020→ O informante do módulo L: Mãe ou responsável = 1, outro morador = 2, não morador = 3

s001→ Na última vez em que esteve grávida fez pré-natal: sim = 1, não = 2

c00701→ Dia de nascimento 

c00702→ Mês de nascimento da criança

c00703→ Ano de nascimento ou idade presumida 

